Train:
  dataset:
    name: SimpleDataset
    data_dir: ./images
    label_file_list: ['./train_labels.json']
    ratio_list: [1.0]

Eval:
  dataset:
    name: SimpleDataset
    data_dir: ./images
    label_file_list: ['./val_labels.json']
    ratio_list: [1.0]

Global:
  save_model_dir: ./output/rec_meter_digits
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: ./pretrained_model
  checkpoints: null
  save_epoch_step: 3
  print_batch_step: 10
  epoch_num: 500
  use_gpu: True
  log_smooth_window: 20
  save_inference_dir: ./output/rec_meter_digits
  infer_img: doc/imgs_words/en/word_10.png
